# GRF-2

##Chapitre 1

###Produit dérivé {-}

Contrat entre 2 partis qui fixe les flux monétaires futurs fondés sur ceux de l'actif sous-jacent(SJ).

###Étapes d'une transaction {-}
1. Acheteur et vendeur se trouve.Facilité par la bourse.
2. Obligations pour les deux partis définis (prix, produits, conditions). Si transaction à la bourse: intermédiaire, et donc, dépôts de garantie possible.
3. Transaction
4. Mise à jour du registre de propriété.

###Mesure d'évaluation taille/activité de la bourse/marché {-}
- Volume de transaction: nombre de titres transigés/périodes
- Valeur marchande: Valeur d'une action/cie/indice boursier
- Positions ouvertes: quantité de contrats qui ne sont pas arrivés à échéance

###Rôle des marchés financiers {-}
- Partage du risque:compagnie partage le risque et les profits avec les actionnaires
- Diversification du risque: risque diversifiable $\rightarrow$ théoriquement possible de diluer le risquepour qu'il devienne nul. Risque non-diversifiable $\rightarrow$ possible de \bold{transférer} le risque via des produits dérivés.

###Utilité des produits dérivés {-}
- Gestion des risques
- Spéculation
- Réduction des frais de transaction
- arbitrage réglementaire

###3 types d'acteurs {-}
- Uilisateurs(acheteur/vendeurs)
- Teneur de marché(intermédiaire)
- Observateur(analyste/autorité)

###Définitions {-}
- Ordre au cours du marché: quantité de l'actif visé à acheter(vendre) au prix du marché, au moment où l'ordre est passée.
- Ordre à cours limité: quantité d'actions à acheter/vendre dans une tranche spécifique de prix.
- Ordre de vente «stop»: prix en -dessous duquel on vend automatiquement.
- Position longue: qui profitera de l'augmentation de la valeur du SJ.
- Position courte: qui profitera de la diminution de la valeur du SJ.
- Vente à découvert: vente d'un actif qu'on ne possède pas. L'actif est livré à une date ultérieur, mais paiement à t=0 au prix de l'actif à t=0.
    * Utilité:
        * Spéculation
        * Financement
        * Couverture contre la baisse de valeur
    * Risque:
        * de défaut
        * de rareté
        
###CAPM(Capital asset pricing management)

3 postulats:
    1. Transactions efficaces et sans friction: pas de frais de transaction, emprunt au taux sans risque.
    2. Rationnalité des investisseurs: maximise leur ratio de Sharpe $\rightarrow\; \frac{E[R_p- r_f]}{\sigma_p}$
    3. Attentes et espérances homogênes




